<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * @see \App\Http\Controllers\DayEventsController
 */
class DayEventsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $day = factory(\App\Day::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('days.events.create', [$day]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $day = factory(\App\Day::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('days.events.index', [$day]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $day = factory(\App\Day::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->post(route('days.events.store', [$day]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\DayEventsController::class,
            'store',
            \App\Http\Requests\StoreEvent::class
        );
    }

    // test cases...
}
