<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * @see \App\Http\Controllers\DocumentPreviewController
 */
class DocumentPreviewControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $document = factory(\App\Document::class)->create();

        $response = $this->get('documents/{document}/preview');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
